clc;
global IN_PATH;
%输入文件夹路径。其中存有6张图片：“front.png”,“left.png”,“right.png”,“up.png”,“down.png”,“back.png”
IN_PATH = './test_imgs/02';
global LGT;
LGT = 200;
global LEN;
LEN = 2;
global FPS;
FPS = 24;
global PSN;
PSN = 4;
cub = get_mgc(IN_PATH);
global hh;
hh = get_pct(cub);
cub = step_1(cub);
cub = step_1(cub);
cub = step_1(cub);
cub = step_1(cub);
cub = step_2(cub);
cub = step_2(cub);
cub = step_2(cub);
cub = step_2(cub);
cub = all_rot(cub, [0; 0; 1]);
cub = all_rot(cub, [0; 0; 1]);
cub = step_3(cub);
cub = step_3(cub);
cub = step_3(cub);
cub = step_3(cub);
cub = step_4(cub);
cub = step_5(cub);
cub = all_rot(cub, [0; 1; 0], true);
cub = step_6(cub);
cub = step_7(cub);